/*Problem Statement
Kajal is analyzing a sequence generated by a data transmission system.

According to the system's design, every number in the sequence should appear exactly twice. However, due to transmission errors, one number appears only once while all other numbers continue to appear exactly twice.

Instead of reporting the faulty number directly, Kajal wants to determine its position in the sorted sequence.

Help Kajal find the unique number and determine its position after the sequence is sorted in non-decreasing order.

Positions are 1-indexed.

Input Format

First line contains an integer N.

Second line contains N space-separated integers.

Output Format

Print two space-separated integers: UniqueNumber Position, where:

UniqueNumber is the number that appears exactly once.

Position is its 1-indexed position in the sorted sequence.

Example
Input
7

4 2 1 2 1 4 9

Output
9 7

Explanation:

After sorting:

1 1 2 2 4 4 9

The number 9 appears exactly once.

Its position in the sorted sequence is: 7

Therefore, the answer is: 9 7

Constraints
1 ≤ N ≤ 10^5
N is always odd
1 ≤ arr[i] ≤ 100
Exactly one number appears once
Every other number appears exactly twice

Hints (3) */
import java.util.*;

public class findUniqueAndPos {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int n = sc.nextInt();
        int[] arr = new int[n];

        int unique = 0;

        for (int i = 0; i < n; i++) {
            arr[i] = sc.nextInt();
            unique ^= arr[i];
        }

        Arrays.sort(arr);

        int position = 0;

        for (int i = 0; i < n; i++) {
            if (arr[i] == unique) {
                position = i + 1; // 1-indexed
                break;
            }
        }

        System.out.println(unique + " " + position);
    }
}